### ISSUE TITLE
Training data is available or not?

### ISSUE THREAD

**Issue by s1530129650** [RecGFI/RecGFI#1]
Dear All,

I'd like to know whether the training data is available or not.

**Comment by mcxwx123** [comment]
Hi Ensheng Shi, you can download the file `issuedata.zip` (the whole dataset for the paper) from [Zenodo](https://zenodo.org/record/5881117) and follow [README.md](https://github.com/mcxwx123/RecGFI/blob/main/README.md) to reproduce the experiments in the paper. Meanwhile, [data_guide.md](https://github.com/mcxwx123/RecGFI/blob/main/data/data_guide.md) is a more detailed description of the dataset.

**Comment by s1530129650** [comment]
Many thanks 😊 ！！！

**Comment by mcxwx123** [comment]
> Many thanks 😊 ！！！

My pleasure : )
